# Database connection (Aiven MySQL)

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Server port
server.port=8080